# Generated by Django 4.1.3 on 2023-01-21 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montante", models.FloatField()),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AL", "Alimentacion"),
                            ("TRANSP", "Transporte"),
                            ("EST", "Estudio"),
                            ("EMP", "Empleo"),
                            ("ENT", "Entretenimiento"),
                            ("CS", "Casa"),
                        ],
                        default="Casa",
                        max_length=30,
                    ),
                ),
            ],
            options={"ordering": ["-fecha"],},
        ),
    ]
