# Generated by Django 3.1.2 on 2022-11-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante', models.FloatField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('AL', 'Alimentacion'), ('TRANSP', 'Transporte'), ('EST', 'Estudio'), ('EMP', 'Empleo'), ('ENT', 'Entretenimiento'), ('CS', 'Casa')], max_length=30)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
