# Generated by Django 4.1.3 on 2022-11-09 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Control_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddPresupuesto_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_presupuesto",
                    models.CharField(
                        choices=[("Gasto", "Gasto"), ("Ingreso", "Ingreso")],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.BigIntegerField()),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Alimento", "Alimento"),
                            ("Viaje", "Viaje"),
                            ("Compras", "Compras"),
                            ("Necesidades", "Necesidades"),
                            ("Entretenimiento", "Entretenimiento"),
                            ("Otro", "Otro"),
                        ],
                        default="Food",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "addpresupuesto",},
        ),
        migrations.CreateModel(
            name="Perfil_Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profesion",
                    models.CharField(
                        choices=[
                            ("Trabajador", "Trabajador"),
                            ("Empresario", "Empresario"),
                            ("Estudiante", "Estudiante"),
                            ("Otro", "Otro"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ahorro", models.IntegerField(blank=True, null=True)),
                ("ingreso", models.BigIntegerField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="Perfil_image")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.DeleteModel(name="Addmoney_info",),
        migrations.DeleteModel(name="UserProfile",),
    ]
