# Generated by Django 3.1.2 on 2022-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AL', 'Alimentacion'), ('TRANSP', 'Transporte'), ('EST', 'Estudio'), ('EMP', 'Empleo'), ('ENT', 'Entretenimiento'), ('CS', 'Casa')], default='Casa', max_length=30),
        ),
    ]
