name: Docker Image CI Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t test2 . -f ./SysCo/Dockerfile
    - name: Create and start virtual environment
      run: |
          python -m venv venv
          source venv/bin/activate
    - name: Test
      run: docker run test2
      
#-f ./SysCo/Dockerfile