name: Docker Image CI Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Prueba
   #   run: docker build -t test2 . -f ./SysCo/Dockerfile
    #- name: Instalar Dependencias
     # run:  pip install
    - name: Test
      run: docker run josepilartes/costco:testing2
      
#-f ./SysCo/Dockerfile